### ISSUE TITLE
Activity reporting is checked by default in the F-droid build

### ISSUE THREAD

**Issue by opk12** [OAndell/Riksdagskollen#15]
Hello. I use F-droid (even on an Android device) because of the proactive, open disclosure for activity reporting ([see wiki](https://f-droid.org/wiki/page/Antifeature:Tracking)) which is clearly labeled. This app is not labeled, so activity reporting does not happen or is opt-in. However, `Dela anonym användnongsinformation` is checked by default. Is that intentional? But issues 2 and 8 suggest the F-droid build does not report activity?

**Comment by gustavaa** [comment]
Thank you for reporting this issue! No crash reporting or collection of analytics is done on the Fdroid app in contrast to what that option appears to suggest. We have two different build flavors, one for Google Play distribution and one for Fdroid. Regarding crash reporting and analytics, this is handled by the `Analytics` class, which have one version for each build flavor. The fdroid version (`app/src/fdroid/java/oscar/riksdagskollen/Analytics.java`) is a dummy implementation and is completely empty. But I will make sure to remove that setting to avoid any confusion on the Fdroid version.
