### ISSUE TITLE
Voteringar: vilken sida hamnar partier som avstår på?

### ISSUE THREAD

**Issue by AntiSC2** [OAndell/Riksdagskollen#3]
Ta till exempel Klimatpolitik, förslagspunkt 8: Vänsterpartiet avstod ifrån att rösta men i snabbvyn så visas dem på Ja-sidan. Istället så kanske det hade varit bättre att sätta dem mellan Ja och Nej.

**Comment by gustavaa** [comment]
Partier som avstår från att rösta dyker nu inte upp alls i voterings-korten. Endast partier som röstar ja eller nej visas i dessa kort.
