### ISSUE TITLE
Problem med F-Droid

### ISSUE THREAD

**Issue by hugo-laestander** [OAndell/Riksdagskollen#8]
Tjenare! 
När man laddar ner appen genom F-Droid så står det att "the source code is no longer available, no updates possible". Så det har blivit något strul där som behöver fixas.

Tack för en riktigt nice app för att få en insyn i vad som händer i vår regering :)

**Comment by gustavaa** [comment]
Hejsan!
Vi är medvetna om detta, men det har blivit krångligt att publicera på F-droid sedan vi la till Firebase crashlytics i appen. Firebase är ett bibliotek som ger väldigt värdefull information om kraschar och buggar, vilket hjälper oss att fixa dessa så fort som möjligt. F-droids kompilering kräver att det inte finns något bibliotek från Google i appen. En potentiell lösning på detta är att ha två olika versioner av källkoden, där en är fri från google-dependencies som vi publicerar på F-droid och en som har google-dependencies som vi publicerar på Google Play. F-droids publiceringsprocess är minst sagt krånglig, men jag jobbar på att försöka få till en sådan lösning.

**Comment by gustavaa** [comment]
Duplicering av [#2](https://github.com/OAndell/Riksdagskollen/issues/2)

**Comment by gustavaa** [comment]
@ReleaseTheKnowledge se svar i den andra [tråden](https://github.com/OAndell/Riksdagskollen/issues/2)

**Comment by gustavaa** [comment]
@ReleaseTheKnowledge Uppdatering kring Fdroid: Vi har nu lyckats reda ut de ovanstående problemen tillsammans med Fdroid och Riksdagskollen är nu återigen publicerad på Fdroid. Vi ber om ursäkt för att det har dröjt.
